# fly.toml app configuration file generated for pimpim-voting on 2024-12-05T20:01:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pimpim-voting'
primary_region = 'cdg'

[mounts]
source = "pimpim_volume"
destination = "/data"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
